version: '2'
services:
  marionete-service:
    container_name: marionete-service
    build:
      context: .
      dockerfile: Dockerfile
    image: marionete-service:latest
    environment:
      ACCOUNT_API_URI: http://localhost:8899
      USER_API_URI: http://localhost:8898
      REST_CLIENT_MAX_RETRIES: 5
      REST_CLIENT_MIN_BACKOFF_S: 1
    ports:
      - 8080:8080
    networks:
      - marionete-network
networks:
  marionete-network:
    driver: bridge